### ISSUE TITLE
プロジェクトローカルに作成した仮想環境をコミット対象外としたい

### ISSUE THREAD

**Issue by 121jigowatts** [shuichi-ochiai/MrSearch#13]
## 背景
プロジェクトディレクトリ配下にPipenvの`.venv`ディレクトリを作成したい。
作成した`.venv`はGitの管理対象外としたい。

## TODO

- [x] .zshrcに`export PIPENV_VENV_IN_PROJECT=true`を記述
- [x] .gitignoreに`.venv`を対象外とする記述を追加

**Comment by miyazak** [comment]
Fixed by #14
