### ISSUE TITLE
slackbotライブラリのインストール

### ISSUE THREAD

**Issue by 121jigowatts** [shuichi-ochiai/MrSearch#4]
## 背景

- PythonのSlack用チャットボットライブラリをインストールする

### インストール
`pip install slackbot`

## TODO

- [ ] [slackbotライブラリ](https://github.com/lins05/slackbot)のインストール

**Comment by miyazak** [comment]
## 参考
[pipenvのインストール方法](https://qiita.com/anvinon/items/5d9c128ef8b65b866dfe)

**Comment by miyazak** [comment]
Fixed by #5
